[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
crypto_lottery = "4d369VWtGANNts4GDJdJZFuJuivHMgA58svruN4Q98zk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
